apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rconman.fullname" . }}-config
  labels:
    {{- include "rconman.labels" . | nindent 4 }}
data:
  config.yaml: |
    server:
      host: "0.0.0.0"
      port: 8080
      base_url: {{ .Values.config.server.baseURL | quote }}
      insecure_mode: {{ .Values.config.server.insecureMode }}
      session_expiry: {{ .Values.config.server.sessionExpiry | quote }}
      session_secret:
        valueFrom:
          env: RCONMAN_SESSION_SECRET
    log:
      level: {{ .Values.config.log.level | quote }}
      format: {{ .Values.config.log.format | quote }}
    store:
      path: {{ .Values.config.store.path | quote }}
      retention: {{ .Values.config.store.retention | quote }}
    auth:
      oidc:
        issuer_url: {{ .Values.config.auth.oidc.issuerURL | quote }}
        client_id:
          valueFrom:
            env: RCONMAN_OIDC_CLIENT_ID
        client_secret:
          valueFrom:
            env: RCONMAN_OIDC_CLIENT_SECRET
{{- with .Values.config.auth.oidc.scopes }}
        scopes:
{{- range . }}
          - {{ . | quote }}
{{- end }}
{{- end }}
      admin:
        claim:
          name: {{ .Values.config.auth.admin.claim.name | quote }}
          value: {{ .Values.config.auth.admin.claim.value | quote }}
{{- with .Values.config.auth.admin.emailAllowlist }}
        email_allowlist:
{{- range . }}
          - {{ . | quote }}
{{- end }}
{{- end }}
{{- with .Values.config.auth.allowlist.emails }}
      allowlist:
        emails:
{{- range . }}
          - {{ . | quote }}
{{- end }}
{{- with $.Values.config.auth.allowlist.domains }}
        domains:
{{- range . }}
          - {{ . | quote }}
{{- end }}
{{- end }}
{{- else }}
{{- with .Values.config.auth.allowlist.domains }}
      allowlist:
        domains:
{{- range . }}
          - {{ . | quote }}
{{- end }}
{{- end }}
{{- end }}
    minecraft:
      servers:
{{- range .Values.config.minecraft.servers }}
        - id: {{ .id | quote }}
          name: {{ .name | quote }}
          rcon:
            host: {{ .rcon.host | quote }}
            port: {{ .rcon.port }}
            password:
              valueFrom:
                env: {{ printf "RCONMAN_MINECRAFT_%s_RCON_PASSWORD" (.id | upper | replace "-" "_") | quote }}
          status_poll_interval: {{ .statusPollInterval | quote }}
{{- with .commands }}
          commands:
            {{- toYaml . | nindent 12 }}
{{- end }}
{{- end }}
