apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rconman.fullname" . }}-config
  labels:
    {{- include "rconman.labels" . | nindent 4 }}
data:
  config.yaml: |
    server:
      host: "0.0.0.0"
      port: 8080
      session_expiry: {{ .Values.config.sessionExpiry | quote }}
    log:
      level: {{ .Values.config.logLevel | quote }}
      format: "text"
    store:
      path: "/data/rconman.db"
      retention: "30d"
