apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rconman.fullname" . }}
  labels:
    {{- include "rconman.labels" . | nindent 4 }}
type: Opaque
data:
  session-secret: {{ .Values.secrets.sessionSecret.value | default "" | b64enc | quote }}
  oidc-client-id: {{ .Values.secrets.oidcClientID.value | default "" | b64enc | quote }}
  oidc-client-secret: {{ .Values.secrets.oidcClientSecret.value | default "" | b64enc | quote }}
  {{- range .Values.secrets.minecraft.servers }}
  {{ printf "minecraft-%s-rcon-password" .id }}: {{ .rconPassword.value | default "" | b64enc | quote }}
  {{- end }}
