apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rconman.fullname" . }}
  labels:
    {{- include "rconman.labels" . | nindent 4 }}
type: Opaque
data:
  session-secret: {{ .Values.secrets.sessionSecret | b64enc | quote }}
  oidc-client-id: {{ .Values.secrets.oidcClientID | b64enc | quote }}
  oidc-client-secret: {{ .Values.secrets.oidcClientSecret | b64enc | quote }}
