// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type CommandLog struct {
	ID         int64     `json:"id"`
	Timestamp  time.Time `json:"timestamp"`
	UserEmail  string    `json:"user_email"`
	ServerID   string    `json:"server_id"`
	Command    string    `json:"command"`
	Response   string    `json:"response"`
	DurationMs int64     `json:"duration_ms"`
	CreatedAt  time.Time `json:"created_at"`
}
