// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"time"
)

const getLogs = `-- name: GetLogs :many
SELECT id, timestamp, user_email, server_id, command, response, duration_ms
FROM command_logs
ORDER BY timestamp DESC
LIMIT ?
`

type GetLogsRow struct {
	ID         int64     `json:"id"`
	Timestamp  time.Time `json:"timestamp"`
	UserEmail  string    `json:"user_email"`
	ServerID   string    `json:"server_id"`
	Command    string    `json:"command"`
	Response   string    `json:"response"`
	DurationMs int64     `json:"duration_ms"`
}

func (q *Queries) GetLogs(ctx context.Context, limit int64) ([]GetLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLogsRow
	for rows.Next() {
		var i GetLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.UserEmail,
			&i.ServerID,
			&i.Command,
			&i.Response,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneOlderThan = `-- name: PruneOlderThan :exec
DELETE FROM command_logs
WHERE timestamp < datetime('now', ?)
`

func (q *Queries) PruneOlderThan(ctx context.Context, datetime interface{}) error {
	_, err := q.db.ExecContext(ctx, pruneOlderThan, datetime)
	return err
}

const recordCommand = `-- name: RecordCommand :exec
INSERT INTO command_logs (timestamp, user_email, server_id, command, response, duration_ms)
VALUES (datetime('now'), ?, ?, ?, ?, ?)
`

type RecordCommandParams struct {
	UserEmail  string `json:"user_email"`
	ServerID   string `json:"server_id"`
	Command    string `json:"command"`
	Response   string `json:"response"`
	DurationMs int64  `json:"duration_ms"`
}

func (q *Queries) RecordCommand(ctx context.Context, arg RecordCommandParams) error {
	_, err := q.db.ExecContext(ctx, recordCommand,
		arg.UserEmail,
		arg.ServerID,
		arg.Command,
		arg.Response,
		arg.DurationMs,
	)
	return err
}
