FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY main.go .
RUN go mod init mock-rcon && go build -o mock-rcon .

FROM alpine:3.21
COPY --from=builder /app/mock-rcon /mock-rcon
EXPOSE 25575
ENTRYPOINT ["/mock-rcon"]
